name: Android Builder

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Building-Apk  
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: amyu/setup-android@v4
      with:
        # default: false
        # Whether to use the cache
        cache-disabled: true        
        # sdk version
        # see https://developer.android.com/studio/releases/platforms
        sdk-version: 26
        # see https://developer.android.com/studio/releases/build-tools
        # It will always be installed.
        build-tools-version: 34.0.0        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Releasing using Hub
      uses: sangatdesai/release-apk@main
      env:
        GITHUB_TOKEN: ${{ secrets.APKBUILDER }}
        APP_FOLDER: app/build/outputs/apk/release/