name: Android-Testers

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Testing-apk
    runs-on: self-hosted
    env:
      DEV_BASE_URL: http://10.0.2.2:5000/
      PROD_BASE_URL: https://staging.groep2.k8s.be/    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install libraries for emulator
        run: |
            sudo apt-get update > /dev/null
            sudo apt-get install -y libpulse0 libx11-6 libxrandr2 libxrender1 libxcursor1 libxinerama1 libxi6 libglu1-mesa libpng16-16 libpulse-dev libqt5widgets5 libqt5gui5 libqt5core5a qemu-kvm libvirt-daemon-system bridge-utils virt-manager udev > /dev/null

      - name: Enable KVM group perms
        run: |
          sudo mkdir -p /etc/udev/rules.d
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules || echo "udevadm not found or unable to reload rules"
          sudo udevadm trigger --name-match=kvm || echo "udevadm not found or unable to trigger rules"      

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          cache-disabled: true        
          sdk-version: 26
          build-tools-version: 34.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > ./local.properties
          echo "DEV_BASE_URL=${{ env.DEV_BASE_URL }}" >> ./local.properties
          echo "PROD_BASE_URL=${{ env.PROD_BASE_URL }}" >> ./local.properties

      - name: Build debug APK
        run: ./gradlew assembleDebug
  
      - name: Run unit tests
        run: ./gradlew test
        
      - name: Update SDK tools
        run: |
          sdkmanager --update > /dev/null 2>&1
          sdkmanager --install 'platform-tools' 'build-tools;34.0.0' 'emulator' 'system-images;android-26;default;x86' > /dev/null 2>&1

      - name: Run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot
          disable-animations: true
          script: ./gradlew connectedCheck      

      - name: Check test result
        if: ${{ failure() }}
        run: echo "Tests failed, please check the artifact."
        
      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/
