name: Android Builder

on:
  push:
    branches:
      - test

jobs:
  Gradle:
    name: Building-Apk  
    runs-on: self-hosted
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Releasing using Hub
      uses: sangatdesai/release-apk@main
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: debug-build